---
- name: Stop Mongo
  become: yes
  systemd:
    name: mongod
    state: stopped

- name: Add mongo config file
  become: yes
  vars:
    conf0: "{{ hostvars[groups['mongo-config-hosts'][0]]['ansible_eth0']['ipv4']['address'] }}"
    conf1: "{{ hostvars[groups['mongo-config-hosts'][1]]['ansible_eth0']['ipv4']['address'] }}"
    conf2: "{{ hostvars[groups['mongo-config-hosts'][2]]['ansible_eth0']['ipv4']['address'] }}"
  template:
    src: mongos.conf.j2
    dest: /etc/mongos.conf
    owner: root
    group: root
    mode: 0644

- name: Add mongos unit file
  become: yes
  template:
    src: mongos.service.j2
    dest: /lib/systemd/system/mongos.service
    owner: root
    group: root
    mode: 0644

- name: Start Mongos
  become: yes
  systemd:
    name: mongos
    state: started