---
- name: Add mongod.conf file
  become: yes
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644

- name: Add mongos unit file
  become: yes
  template:
    src: mongod.service.j2
    dest: /lib/systemd/system/mongod.service
    owner: root
    group: root
    mode: 0644

- name: Start Mongod
  become: yes
  systemd:
    name: mongod
    state: started

- name: Initialize ReplicaSet
  vars:
    conf0: "{{ hostvars[groups['mongo-shard-0-hosts'][0]]['ansible_eth0']['ipv4']['address'] }}"
    conf1: "{{ hostvars[groups['mongo-shard-0-hosts'][1]]['ansible_eth0']['ipv4']['address'] }}"
  command: "mongo localhost:27017 --eval 'printjson(rs.initiate({ _id: \"{{ repl_set_name }}\", members: [ { _id: 0, host: \"{{ conf0 }}:27017\" }, { _id: 1, host: \"{{ conf1 }}:27017\" } ] }))'"